# Minimal SQLAlchemy Core tables needed by the worker skeleton.

from sqlalchemy import BigInteger, Boolean, Column, DateTime, Integer, JSON, MetaData, String, Table, Text, Uuid

metadata = MetaData()

analysis_jobs = Table(
    "analysis_jobs",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("case_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("status", String(50), nullable=False),
    Column("os_family", String(20), nullable=False),
    Column("os_version", String(255)),
    Column("architecture", String(100)),
    Column("kernel_version", String(255)),
    Column("symbol_table", String(255)),
    Column("plugin_profile", String(100)),
    Column("requested_plugins", JSON),
    Column("error_message", Text),
    Column("duration_ms", Integer),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

evidences = Table(
    "evidences",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("case_id", Uuid(), nullable=False),
    Column("source_type", String(50), nullable=False),
    Column("original_filename", String(255), nullable=False),
    Column("size_bytes", BigInteger),
    Column("md5", String(32)),
    Column("sha256", String(64)),
    Column("storage_bucket", String(255)),
    Column("storage_key", String(1024)),
    Column("local_path", String(1024)),
    Column("os_family", String(20), nullable=False),
    Column("os_version", String(255)),
    Column("architecture", String(100)),
    Column("kernel_version", String(255)),
    Column("symbol_table", String(255)),
    Column("acquisition_tool", String(255)),
    Column("acquisition_time", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

plugin_results = Table(
    "plugin_results",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("os_family", String(20), nullable=False),
    Column("plugin_profile", String(100)),
    Column("plugin_name", String(255), nullable=False),
    Column("source_plugin", String(255), nullable=False),
    Column("status", String(50), nullable=False),
    Column("raw_output_bucket", String(255)),
    Column("raw_output_key", String(1024)),
    Column("parsed_output_bucket", String(255)),
    Column("parsed_output_key", String(1024)),
    Column("parsed_record_count", Integer),
    Column("error_message", Text),
    Column("duration_ms", Integer),
    Column("extra_data", JSON),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

process_artifacts = Table(
    "process_artifacts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("raw_record", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("pid", Integer),
    Column("ppid", Integer),
    Column("name", String(255)),
    Column("image_path", String(1024)),
    Column("command_line", Text),
    Column("user_name", String(255)),
    Column("session_id", Integer),
    Column("created_time", DateTime(timezone=True)),
    Column("exited_time", DateTime(timezone=True)),
    Column("is_hidden_candidate", Boolean, nullable=False),
)

network_artifacts = Table(
    "network_artifacts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("raw_record", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("protocol", String(50)),
    Column("local_address", String(255)),
    Column("local_port", Integer),
    Column("remote_address", String(255)),
    Column("remote_port", Integer),
    Column("state", String(100)),
    Column("pid", Integer),
    Column("process_name", String(255)),
    Column("created_time", DateTime(timezone=True)),
)

module_artifacts = Table(
    "module_artifacts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("raw_record", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("pid", Integer),
    Column("process_name", String(255)),
    Column("module_name", String(255)),
    Column("module_path", String(1024)),
    Column("base_address", String(100)),
    Column("size_bytes", BigInteger),
    Column("load_time", DateTime(timezone=True)),
)

memory_region_artifacts = Table(
    "memory_region_artifacts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("raw_record", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("pid", Integer),
    Column("process_name", String(255)),
    Column("start_address", String(100)),
    Column("end_address", String(100)),
    Column("protection", String(100)),
    Column("is_executable", Boolean, nullable=False),
    Column("is_private", Boolean, nullable=False),
    Column("description", Text),
    Column("hexdump_excerpt", Text),
    Column("disassembly_excerpt", Text),
)

command_artifacts = Table(
    "command_artifacts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("raw_record", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("pid", Integer),
    Column("process_name", String(255)),
    Column("command", Text),
    Column("shell_type", String(100)),
    Column("user_name", String(255)),
    Column("executed_at", DateTime(timezone=True)),
)

yara_matches = Table(
    "yara_matches",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("rule_name", String(255), nullable=False),
    Column("namespace", String(255)),
    Column("tags", JSON),
    Column("target_type", String(100)),
    Column("target_identifier", String(255)),
    Column("offset", Integer),
    Column("matched_text_excerpt", Text),
    Column("extra_data", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

risk_findings = Table(
    "risk_findings",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("analysis_job_id", Uuid(), nullable=False),
    Column("evidence_id", Uuid(), nullable=False),
    Column("plugin_result_id", Uuid()),
    Column("os_family", String(20), nullable=False),
    Column("os_scope", String(20), nullable=False),
    Column("source_plugin", String(255)),
    Column("rule_id", String(255)),
    Column("rule_name", String(255)),
    Column("category", String(100)),
    Column("severity", String(20), nullable=False),
    Column("score", Integer, nullable=False),
    Column("title", String(255), nullable=False),
    Column("description", Text),
    Column("artifact_type", String(100)),
    Column("artifact_id", String(100)),
    Column("recommendation", Text),
    Column("extra_data", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)
